### ISSUE TITLE
Where to report bugs

### ISSUE THREAD

**Issue by cpansprout** [briandfoy/geo-geonames#12]
The POD documentation says to report bugs at rt.cpan.org, but the META files point to GitHub.  Ideally they should point to the same place.  (Should I report this to rt? :-)

**Comment by briandfoy** [comment]
GitHub would work nicely. If you'd like to make the change to be consistent in both places you'll become a contributor :)

**Comment by briandfoy** [comment]
Fixed in acebe562b453526e75521c510626b9498c62cbab .
