### ISSUE TITLE
Geo-GeoNames-1.101 < Geo-GeoNames-1.11

### ISSUE THREAD

**Issue by eserte** [briandfoy/geo-geonames#14]
It seems that the intention is that 1.101 should be newer than 1.11, as it was released later, but perl's versioning rules are different. For example, https://metacpan.org/release/Geo-GeoNames still points to 1.11.

**Comment by nicomen** [comment]
This should be fixed by 1.12 in commit https://github.com/briandfoy/geo-geonames/commit/9538b5bbf473582907d87e164d370191f8158ad6 and released here: http://search.cpan.org/~nicomen/Geo-GeoNames-1.12/

Thanks for yout report.
